---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: hello-world-namespace
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        # name in manifest is optional and defaults to Object name
        name: mylittlenamespace
        labels:
          foo: "bar"
  providerConfigRef:
    name: cs-workload-cluster
