apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: capicluster.api.scs.community
spec:
  resources:
  - name: Cluster
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha2
      kind: Object
      metadata:
        name: TO-BE-SET
      spec:
        providerConfigRef:
          name: capi-moin-cluster
        forProvider:
          manifest:
            apiVersion: cluster.x-k8s.io/v1beta1
            kind: Cluster
            metadata:
              name: TO-BE-SET
              namespace: kaas-playground9
              labels:
                managed-secret: cloud-config
            spec:
              clusterNetwork:
                pods:
                  cidrBlocks:
                    - 192.168.0.0/16
                serviceDomain: cluster.local
                services:
                  cidrBlocks:
                    - 10.96.0.0/12
              topology:
                variables:
                  - name: controller_flavor
                    value: "SCS-2V-4-50"
                  - name: worker_flavor
                    value: "SCS-2V-4-50"
                  - name: external_id
                    value: ebfe5546-f09f-4f42-ab54-094e457d42ec # gx-scs
                class: openstack-scs-1-29-v1
                controlPlane:
                  replicas: 1
                version: TO-BE-SET #v1.29.0
                workers:
                  machineDeployments:
                    - class: openstack-scs-1-29-v1
                      failureDomain: nova
                      name: md-0
                      replicas: 2
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.version
      toFieldPath: spec.forProvider.manifest.spec.topology.version
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.name
      toFieldPath: spec.forProvider.manifest.metadata.name
      transforms:
      - type: string
        string:
          type: Format
          fmt: "%s-capi"
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.claimRef.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          type: Format
          fmt: "%s-capi"
      policy:
        fromFieldPath: Required
  compositeTypeRef:
    apiVersion: api.scs.community/v1alpha1
    kind: XCluster
