---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: mylittleshootcluster
spec:
  providerConfigRef:
    name: sa-gardener-apiserver
  forProvider:
    manifest:
      kind: Shoot
      apiVersion: core.gardener.cloud/v1beta1
      metadata:
        namespace: garden-ylgloie5sy
        name: a680ybrrib
      spec:
        provider:
          type: openstack
          infrastructureConfig:
            apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
            kind: InfrastructureConfig
            networks:
              workers: 10.250.0.0/16
            floatingPoolName: public
          controlPlaneConfig:
            apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
            kind: ControlPlaneConfig
            loadBalancerProvider: amphora
          workers:
            - cri:
                name: containerd
              machine:
                type: SCS-2V-4
                image:
                  name: gardenlinux
                  version: 1443.3.0
                architecture: amd64
              volume:
                type: ssd
                size: 50Gi
              zones:
                - nova
              name: worker-oajkj
              minimum: 1
              maximum: 2
              maxSurge: 1
        networking:
          nodes: 10.250.0.0/16
          type: calico
        cloudProfileName: regiocloud
        secretBindingName: default-openstack-secret
        region: RegionA
        purpose: production
        kubernetes:
          version: 1.29.5
          enableStaticTokenKubeconfig: false
        addons:
          kubernetesDashboard:
            enabled: false
          nginxIngress:
            enabled: false
        maintenance:
          timeWindow:
            begin: 220000+0200
            end: 230000+0200
          autoUpdate:
            kubernetesVersion: true
            machineImageVersion: true
        hibernation:
          schedules: []
