apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: template-cluster
spec:
  credentials:
    source: Secret
    secretRef:
      key: kubeconfig
      name: template-service-account
      namespace: crossplane-system
