apiVersion: v1
kind: Secret
metadata:
  name: k8s-cluster-config
  namespace: crossplane-system
data:
  kubeconfig: YXBpVmVyc2lvbjogdjEKY...
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: cs-workload-cluster
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: k8s-cluster-config
      key: kubeconfig
