apiVersion: v1
kind: Secret
metadata:
  name: k8s-clusterstacksmanagementcluster-config
  namespace: crossplane-system
data:
  kubeconfig: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6...
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: cs-mgmt-cluster
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: k8s-clusterstacksmanagementcluster-config
      key: kubeconfig
