---
apiVersion: kubernetes.crossplane.io/v1alpha2
kind: Object
metadata:
  name: mylittleworkloadcluster
spec:
  forProvider:
    manifest:
      apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      metadata:
        name: mylittleworkloadcluster
        namespace: hkthn
        labels:
          managed-secret: cloud-config
      spec:
        clusterNetwork:
          pods:
            cidrBlocks:
              - 192.168.0.0/16
          serviceDomain: cluster.local
          services:
            cidrBlocks:
              - 10.96.0.0/12
        topology:
          variables:
            - name: controller_flavor
              value: "SCS-2V-4-50"
            - name: worker_flavor
              value: "SCS-2V-4-50"
            - name: external_id
              value: "ebfe5546-f09f-4f42-ab54-094e457d42ec" # gx-scs
          class: openstack-alpha-1-28-v3
          controlPlane:
            replicas: 1
          version: v1.28.6
          workers:
            machineDeployments:
              - class: capi-openstack-alpha-1-28
                failureDomain: nova
                name: capi-openstack-alpha-1-28
                replicas: 2
  providerConfigRef:
    name: cs-mgmt-cluster
